<a href="https://colab.research.google.com/github/JmercyA/PYTHON-/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Exercise 1:Create tup variable with (1, 2, 3) in Tuple format, then save it as a Numpy Array to
#tup_arr variable
tup = (1,2,3)
tup_array=np.array(tup)
tup_array

array([1, 2, 3])

In [7]:
# Exercise 2: . Copy tup_arr to variable tup_arr_copy .(Hint: .copy() )
tup_array_copy = tup_array.copy()
tup_array_copy

array([1, 2, 3])

In [9]:
#Change the first element of tup_arr to 0, then output tup_arr and tup_arr_copy to check the first element.
tup_array[0] = 0
tup_array


array([0, 2, 3])

In [ ]:
#Creating an array of a single value
#np.zeros() - a numpy array with zeros.
#np.ones() - a numpy array with ones.
#np.full() - a numpy array with a given fill_value.

In [18]:
# Creating a matrix of 3 rows and 2 columns of 0
A = np.zeros(shape=(3,2), dtype=np.float64)
A

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
# Creating a matrix of 3 rows and 2 columns of 1
A = np.ones(shape=(3,2), dtype=np.float64)
A

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
# Creating a matrix of 3 rows and 2 columns of 3 in a floating-point
A = np.full(shape=(3,2), fill_value=5., dtype=np.float64)
A

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [ ]:
#Creating an array with shape and type as a given array
#np.zeros_like()
#np.ones_like()
#np.full_like()

In [23]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [27]:
# Creating an array of zeros with the same shape and type as ‘A’
np_zero = np.zeros_like(A, dtype=np.int64)
np_zero

array([0, 0, 0, 0, 0])

In [29]:
np.ones = np.ones_like(np_zero , dtype=np.int64)
np.ones

array([1, 1, 1, 1, 1])

In [32]:
# Creating an array of thirteens(13) with the same shape and type as ‘A’
np_full = np.full_like(A, fill_value=13, dtype=np.int64)
np_full

array([13, 13, 13, 13, 13])

In [35]:
#Creating an array of values over a specified interval With numpy, you can create an array with numbers at a specified interval.
#For instance, You can create an array consisting of consecutive values from 1 to 10 at regular intervals,using the following numpy functions.
#np.linspace() - to create an array consisting of evenly spaced numbers over a specified interval.
#np.arange() - to create an array consisting of evenly spaced numbers within a given interval.

# Generating 19 values from 1(inclusive) to 10(exclusive) at equal intervals
np.linspace(start=1,stop=10, num=19)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [41]:
# Generating values from 1(inclusive) to 10(exclusive) in every 0.5
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
#Create a Numpy Array that has all elements as 3, and with 2 rows and 4 columns. Assign it to variable arr6

In [49]:
arr6 = np.full(shape=(2,4), fill_value=3., dtype=np.float64)
arr6

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [52]:
# Create a Numpy Array that has same shape as arr6 and all elements as 0. Assign it to variable arr7
arr7 = np.full_like(arr6,fill_value = 0, dtype = np.int64)
arr7


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
#Create a Numpy Array that has 10 elements, which spans from 1 to 19 in equal intervals.Assign it to variable arr8
arr8 =np.linspace (1,19,10)
arr8

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [ ]:
#Create a Numpy Array that spans from 1 to 19, increasing by 4. Assign it to variable arr9 .

In [60]:
arr9 = np.arange (1,19,4)
arr9

array([ 1,  5,  9, 13, 17])

In [61]:
scores = np.array([
 [80, 92, 70, 65, 92], # Report card of student 0
 [91, 75, 90, 68, 85], # Report card of student 1
 [86, 76, 42, 72, 88], # Report card of student 2
 [77, 92, 52, 60, 80], # Report card of student 3
 [75, 85, 85, 92, 95], # Report card of student 4
 [96, 90, 95, 81, 72] # Report card of student 5
])
scores

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

In [62]:
scores[2, 0]

86

In [63]:
scores[4, 4]

95

In [ ]:
#Year Sea Air
#Year1 4,290 6,070
#Year2 4,425 6,278
#Year3 4,577 6,350
#Year4 4,617 8,295
#Year5 4,491 10,780
#Store the above table in Numpy Array format, to variable cargo_n_array . (Store only the integer values.)

In [66]:
cargo_n_array1 ={'4290': 6070 , "4425" : 6278 , "4577" : 6350 , "4617" : 8295 , "4491" : 10780}
cargo_n_array1

{'4290': 6070, '4425': 6278, '4577': 6350, '4617': 8295, '4491': 10780}

In [78]:
cargo_n_array = np.array([
 [4290, 6070],
 [4425, 6278],
 [4577, 6350],
 [4617, 8295],
 [4491, 10780]
])
cargo_n_array

array([[ 4290,  6070],
       [ 4425,  6278],
       [ 4577,  6350],
       [ 4617,  8295],
       [ 4491, 10780]])

In [79]:
#Retrieve Year1's number of air import/export from cargo_n_array
cargo_n_array[0, 1]

6070

In [80]:
# row=1, col=all
scores[1,:]

array([91, 75, 90, 68, 85])

In [81]:
# row=3, col=all
scores[3]

array([77, 92, 52, 60, 80])

In [82]:
#Scores for student 1, 2, 3 and 4 in all subjects
scores[1:5]

array([[91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95]])

In [83]:
#Scores for student 2, 3, 4 and 5 in all subjects
scores[2:6]

array([[86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

In [ ]:
#Scores of all even-numbered students

In [85]:
scores[0:6:2]

array([[80, 92, 70, 65, 92],
       [86, 76, 42, 72, 88],
       [75, 85, 85, 92, 95]])

In [86]:
#Scores of all odd-numbered students
scores[1:6:2]

array([[91, 75, 90, 68, 85],
       [77, 92, 52, 60, 80],
       [96, 90, 95, 81, 72]])

In [ ]:
#Selecting elements of specific columns (axis=1) if you want to specify only the columns while selecting all rows, use [:, column_index] for a singlecolumn selection
# or [:, start:stop:step] for the selection of a specific range of columns.
StudentID History English Math Social Studies Science
0 80 92 70 65 92
1 91 75 90 68 85
2 86 76 42 72 88
3 77 92 52 60 80
4 75 85 85 92 95
5 96 90 95 81 72

In [87]:
scores = np.array([
 [80, 92, 70, 65, 92], # Report card of student 0
 [91, 75, 90, 68, 85], # Report card of student 1
 [86, 76, 42, 72, 88], # Report card of student 2
 [77, 92, 52, 60, 80], # Report card of student 3
 [75, 85, 85, 92, 95], # Report card of student 4
 [96, 90, 95, 81, 72] # Report card of student 5
])
scores

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

In [96]:
#Scores in History for all students
scores[ :,0]

array([80, 91, 86, 77, 75, 96])

In [95]:
#Scores in Math for all students
scores[ :,2]

array([70, 90, 42, 52, 85, 95])

In [97]:
#Scores in History, English and Math for all students
scores[ :,0:3]

array([[80, 92, 70],
       [91, 75, 90],
       [86, 76, 42],
       [77, 92, 52],
       [75, 85, 85],
       [96, 90, 95]])

In [98]:
midterm_scores = np.array([
 [80, 92, 70, 65, 92],
 [91, 75, 90, 68 ,85],
 [86, 76, 42, 72, 88],
 [77, 92, 52, 60, 80],
 [75, 85, 85, 92, 95],
 [96, 90, 95, 81, 72]
])
final_scores = np.array([
 [85, 95, 90, 66, 93],
 [93, 70, 80, 60, 81],
 [89, 78, 55, 75, 80],
 [80, 94, 59, 72, 90],
 [70, 82, 81, 95, 72],
 [90, 76, 93, 82, 89]
])
final_scores.shape

(6, 5)

#1. Numpy methods for aggregate operations

In [ ]:
#1.sum() calculates the total sum of an array.

In [99]:
#Total score in the midterm exam
midterm_scores.sum()

2399

In [100]:
#Total score in the final exam
final_scores.sum()

2415

In [101]:
#Total score of student 0
midterm_scores[0,:].sum()

399

In [ ]:
# 2.np.mean()
# .mean() calculates the average value of an array.

In [104]:
#Average score in the midterm
midterm_score_mean = midterm_scores.mean()
midterm_score_mean.round(2)

79.97

In [105]:
#Average score of student 4 in the midterm
midterm_scores[4,:].mean()

86.4

In [107]:
#Top score in the final exam
final_scores.max()

95

In [109]:
#Highest score of student 2 in the final exam
final_scores[2,:].max()

89

In [ ]:
#np.stack()
#np.stack() joins a sequence of arrays along a new axis. Note that the stacked array has one more dimension than before.

In [110]:
#Joining midterm and final exam scores into a new array
scores = np.stack([midterm_scores,final_scores])
print(scores.shape)
scores

(2, 6, 5)


array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

In [111]:
#np.all()
#.all() tests whether or not all array elements alongside the given axis are true It returns 'True' if all elements are true, or 'False' otherwise.
#Checking who scored 90 or higher in both English exams
np.all(scores[:,:,1]>=90, axis=0)

array([ True, False, False,  True, False, False])

In [ ]:
#Students with a score of 50 or less in both Math exams

In [112]:
#np.any()
#np.any returns True if any array element on the given axis is true, and False otherwise.
#When np.any() is used on two arrays, it proceeds an element-wise comparison of two arrays returning True if there is any matching pair.
#Students with a score of 50 or less in both Math exams
np.any(scores[:,:,2]<=50, axis=0)

array([False, False,  True, False, False, False])

In [ ]:
#Student 2 scored 50 or less twice in a row

In [114]:
# np.unique()
 #.unique() returns the unique elements of an array.
np.unique(scores) #Only the unique exam scores are returned without duplicates

array([42, 52, 55, 59, 60, 65, 66, 68, 70, 72, 75, 76, 77, 78, 80, 81, 82,
       85, 86, 88, 89, 90, 91, 92, 93, 94, 95, 96])

In [ ]:
#Broadcasting
#The term "broadcasting" describes how numpy treats arrays with different shapes during arithmetic
#operations. The array with the fewer axes is considered a smaller array, and the other one is a larger array.
#numpy expands the domain of operations over arrays by adjusting the shape of the smaller array to that
#of the larger array or reshaping both arrays to the level of operation-compatible.

In [116]:
A = np.arange(3)
A

array([0, 1, 2])

In [118]:
B = A + 5
B

array([5, 6, 7])

In [121]:
C = np.arange(3).reshape((3,1))
C

array([[0],
       [1],
       [2]])

In [126]:
#Year Sea Air
#Year1 4,290 6,070
#Year2 4,425 6,278
#Year3 4,577 6,350
#Year4 4,617 8,295
#Year5 4,491 10,780

# Example1: Store above table in Numpy Array format, to variable cargo_n . (Store only integer values.)
cargo_n_array = np.array([[4290, 6070],
                   [4425, 6278],
                   [4577, 6350],
                   [4617, 8295],
                   [4491, 10780]])

In [129]:
#Exercise2. The unit of cargo_n_array is per 1000. Dividing by 1000, change the unit to one million.
#(Hint: Broadcasting Rule 1)
cargo_n_array2 = cargo_n_array/1000
cargo_n_array2

array([[ 4.29 ,  6.07 ],
       [ 4.425,  6.278],
       [ 4.577,  6.35 ],
       [ 4.617,  8.295],
       [ 4.491, 10.78 ]])

In [135]:
#Exercise3. Calculate the annual number of import/exports from cargo_n_array , then store it to cargo_yearly_sum . (Hint: Refer to .sum(axis=1) method.)
cargo_yearly_sum = cargo_n_array[:,1].sum()
cargo_yearly_sum

37773

In [137]:
cargo_yearly_sum = cargo_n_array.sum(axis = 1)
cargo_yearly_sum

array([10360, 10703, 10927, 12912, 15271])

In [138]:
cargo_yearly_sum.reshape(5,1) / cargo_yearly_sum.reshape(1,5)

array([[1.        , 0.96795291, 0.94811019, 0.8023544 , 0.67841006],
       [1.03310811, 1.        , 0.97950032, 0.82891884, 0.70087093],
       [1.05472973, 1.02092871, 1.        , 0.84626704, 0.71553926],
       [1.24633205, 1.20639073, 1.18166011, 1.        , 0.8455242 ],
       [1.47403475, 1.42679623, 1.39754736, 1.18269827, 1.        ]])